### ISSUE TITLE
Access defining formula of identifier as has part qualifier value in SPARQL

### ISSUE THREAD

**Issue by philsMINT** [ag-gipp/MathQA#2]
The following query (aiming to retrieve the gas constant identifier item Q182333 from the gas equation item Q11432) does not work, because it departs from the triple format:

> #find has part qualifier values with defining formula 'R'
> SELECT ?identifierLabel ?symbol WHERE {
>   wd:Q11432 wdt:P527 ?identifier wdt:P2534 ?symbol.
>   SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
>   FILTER(STR(?symbol) = 'R')
> }

Instead, only this one works:

> #find has part property items with quantity symbol 'R'
> SELECT ?identifierLabel ?symbol WHERE {
>   wd:Q11432 wdt:P527 ?identifier.
>   ?identifier wdt:P416 ?symbol.
>   SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
>   FILTER(STR(?symbol) = 'R')
> }

In the latter case, the problem is that only the quantity symbol property P416 can be queried from the gas constant identifier item Q182333, and not, as intended, the has part qualifier defining formula value from the gas equation item Q11432 .

**Comment by physikerwelt** [comment]
I tested the second one, i.e.,
```SPARQL
#find has part properties with formula 'R'
SELECT ?identifierLabel ?symbol WHERE {
wd:Q11432 wdt:P527 ?identifier.
?identifier wdt:P2534 ?symbol.
SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
FILTER(STR(?symbol) = 'R')
}
```
 and get 0 results c.f. http://tinyurl.com/y8dudkfk 
@philsMINT can you please double check the input and update the task

**Comment by philsMINT** [comment]
updated

**Comment by physikerwelt** [comment]
@philsMINT did you look at the [mona lisa qualifiers example](https://www.wikidata.org/wiki/Wikidata:SPARQL_tutorial#Qualifiers)?

**Comment by physikerwelt** [comment]
I made the listing part http://tinyurl.com/yc9p2h7f
... the filtering part remains as exercise ;-)
